/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.pokedex.view;


import br.com.pokedex.dao.BatalhaDAO;
import br.com.pokedex.model.Batalha;
import br.com.pokedex.model.PokedexUtil;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;

import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nanda
 */
public class BatalhaForm extends javax.swing.JFrame {

    // Metodo listar na tabela
    public void listar_treinador() {

        BatalhaDAO dao = new BatalhaDAO();
        List<Batalha> batalhaList = dao.listar_batalhas();
        DefaultTableModel dados = (DefaultTableModel) tabelaBatalha.getModel();
        dados.setNumRows(0);

        for (Batalha b : batalhaList) {
            dados.addRow(new Object[]{
                b.getEnderecoGinasio(),
                b.getCpfTreinador(),
                b.getAdversario(),
                b.getStatus(),
                b.getVencedor()
            });
        }
    }

    /**
     * Creates new form TreinadorForm
     */
    public BatalhaForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon = new ImageIcon(getClass().getResource("/images/BatalhaDir.png"));
        Image image = icon.getImage();
        jDesktopPane1 = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){
                g.drawImage(image, 0, 0, 900, 550, this);
            }
        };
        telaTreinadores = new javax.swing.JTabbedPane();
        abaCadastro = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtAdversario = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtCpf = new javax.swing.JFormattedTextField();
        boxStatus = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtVencedor = new javax.swing.JTextField();
        abaPesquisa = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtPesquisa = new javax.swing.JTextField();
        buttonSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaBatalha = new javax.swing.JTable();
        buttonNew = new javax.swing.JButton();
        buttonSave = new javax.swing.JButton();
        buttonEdit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jDesktopPane1.setPreferredSize(new java.awt.Dimension(900, 544));

        telaTreinadores.setBackground(new java.awt.Color(122, 122, 122));
        telaTreinadores.setForeground(new java.awt.Color(0, 0, 0));
        telaTreinadores.setFont(new java.awt.Font("NATS", 0, 16));
        telaTreinadores.setPreferredSize(new java.awt.Dimension(867, 274));

        abaCadastro.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("NATS", 0, 16));
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Adversário:");

        txtAdversario.setBackground(new java.awt.Color(255, 255, 255));
        txtAdversario.setFont(new java.awt.Font("NATS", 0, 16));
        txtAdversario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAdversarioActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("NATS", 0, 16));
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Endereço:");

        txtEndereco.setBackground(new java.awt.Color(255, 255, 255));
        txtEndereco.setFont(new java.awt.Font("NATS", 0, 16));
        txtEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnderecoActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("NATS", 0, 16));
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("CPF Treinador:");

        txtCpf.setBackground(new java.awt.Color(255, 255, 255));
        try {
            txtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpf.setFont(new java.awt.Font("NATS", 0, 16));
        txtCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCpfActionPerformed(evt);
            }
        });

        boxStatus.setFont(new java.awt.Font("NATS", 0, 16));
        boxStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Em andamento", "Cancelada", "Concluída" }));
        boxStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxStatusActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("NATS", 0, 16));
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Status:");

        jLabel4.setFont(new java.awt.Font("NATS", 0, 16));
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Vencedor:");

        txtVencedor.setBackground(new java.awt.Color(255, 255, 255));
        txtVencedor.setFont(new java.awt.Font("NATS", 0, 16));
        txtVencedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVencedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout abaCadastroLayout = new javax.swing.GroupLayout(abaCadastro);
        abaCadastro.setLayout(abaCadastroLayout);
        abaCadastroLayout.setHorizontalGroup(
            abaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaCadastroLayout.createSequentialGroup()
                .addGroup(abaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(abaCadastroLayout.createSequentialGroup()
                        .addGroup(abaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(abaCadastroLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, abaCadastroLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(abaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
                            .addComponent(txtAdversario))
                        .addGap(29, 29, 29)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(abaCadastroLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(boxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtVencedor, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        abaCadastroLayout.setVerticalGroup(
            abaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaCadastroLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(abaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(abaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAdversario, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(abaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(boxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtVencedor, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(122, Short.MAX_VALUE))
        );

        telaTreinadores.addTab("Dados cadastrais", abaCadastro);

        abaPesquisa.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("NATS", 0, 16));
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nome:");

        txtPesquisa.setBackground(new java.awt.Color(255, 255, 255));
        txtPesquisa.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        txtPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisaActionPerformed(evt);
            }
        });
        txtPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPesquisaKeyPressed(evt);
            }
        });

        buttonSearch.setBackground(new java.awt.Color(153, 153, 153));
        buttonSearch.setFont(new java.awt.Font("NATS", 0, 16));
        buttonSearch.setForeground(new java.awt.Color(0, 0, 0));
        buttonSearch.setText("Pesquisar");
        buttonSearch.setBorderPainted(false);
        buttonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSearchActionPerformed(evt);
            }
        });

        tabelaBatalha.setFont(new java.awt.Font("NATS", 0, 16));
        tabelaBatalha.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Endereço", "Treinador", "Adversário", "Status", "Vencedor"
            }
        ));
        tabelaBatalha.setSelectionBackground(new java.awt.Color(117, 117, 117));
        tabelaBatalha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaBatalhaMouseClicked(evt);
            }
        });
        tabelaBatalha.getTableHeader().setFont(new java.awt.Font("NATS", 0, 16));
        tabelaBatalha.getTableHeader().setPreferredSize(new Dimension(50, 30));
        tabelaBatalha.getTableHeader().setBackground(new java.awt.Color(60,63,65));
        jScrollPane1.setViewportView(tabelaBatalha);
        tabelaBatalha.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout abaPesquisaLayout = new javax.swing.GroupLayout(abaPesquisa);
        abaPesquisa.setLayout(abaPesquisaLayout);
        abaPesquisaLayout.setHorizontalGroup(
            abaPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaPesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(382, Short.MAX_VALUE))
            .addGroup(abaPesquisaLayout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        abaPesquisaLayout.setVerticalGroup(
            abaPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaPesquisaLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(abaPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE))
        );

        telaTreinadores.addTab("Pesquisar", abaPesquisa);

        buttonNew.setBackground(new java.awt.Color(153, 153, 153));
        buttonNew.setFont(new java.awt.Font("NATS", 0, 16));
        buttonNew.setForeground(new java.awt.Color(0, 0, 0));
        buttonNew.setText("Novo");
        buttonNew.setBorder(null);
        buttonNew.setBorderPainted(false);
        buttonNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNewActionPerformed(evt);
            }
        });

        buttonSave.setBackground(new java.awt.Color(153, 153, 153));
        buttonSave.setFont(new java.awt.Font("NATS", 0, 16));
        buttonSave.setForeground(new java.awt.Color(0, 0, 0));
        buttonSave.setText("Criar");
        buttonSave.setBorderPainted(false);
        buttonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveActionPerformed(evt);
            }
        });

        buttonEdit.setBackground(new java.awt.Color(153, 153, 153));
        buttonEdit.setFont(new java.awt.Font("NATS", 0, 16));
        buttonEdit.setForeground(new java.awt.Color(0, 0, 0));
        buttonEdit.setText("Salvar");
        buttonEdit.setBorderPainted(false);
        buttonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(telaTreinadores, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(buttonNew, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(buttonSave, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(buttonEdit, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(telaTreinadores, javax.swing.GroupLayout.PREFERRED_SIZE, 867, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonNew, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(331, 331, 331))
        );

        jDesktopPane1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {buttonEdit, buttonNew, buttonSave});

        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(telaTreinadores, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                .addGap(81, 81, 81)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buttonSave)
                        .addComponent(buttonEdit))
                    .addComponent(buttonNew, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83))
        );

        jDesktopPane1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {buttonEdit, buttonNew, buttonSave});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // Carrega a lista
        listar_treinador();
    }//GEN-LAST:event_formWindowActivated

    private void txtAdversarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAdversarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAdversarioActionPerformed

    private void txtEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnderecoActionPerformed

    private void txtPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisaActionPerformed

    private void txtPesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaKeyPressed
        //Pesquisa ao digitar
        //Pesquisar treinador por nome
        String nome = "%" + txtPesquisa.getText() + "%";

        BatalhaDAO dao = new BatalhaDAO();
        List<Batalha> batalhaList = dao.buscar_batalha_Treinador(nome);
        DefaultTableModel dados = (DefaultTableModel) tabelaBatalha.getModel();
        dados.setNumRows(0);

        for (Batalha b : batalhaList) {
            dados.addRow(new Object[]{
                b.getEnderecoGinasio(),
                b.getCpfTreinador(),
                b.getAdversario(),
                b.getStatus(),
                b.getVencedor()
            });
        }
    }//GEN-LAST:event_txtPesquisaKeyPressed

    private void buttonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSearchActionPerformed
        //Pesquisar treinador por nome
        String cpf = "%" + txtPesquisa.getText() + "%";

        BatalhaDAO dao = new BatalhaDAO();
        List<Batalha> batalhaList = dao.buscar_batalha_Treinador(cpf);
        DefaultTableModel dados = (DefaultTableModel) tabelaBatalha.getModel();
        dados.setNumRows(0);

        for (Batalha b : batalhaList) {
            dados.addRow(new Object[]{
                b.getEnderecoGinasio(),
                b.getCpfTreinador(),
                b.getAdversario(),
                b.getStatus(),
                b.getVencedor()
            });
        }
    }//GEN-LAST:event_buttonSearchActionPerformed

    private void tabelaBatalhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaBatalhaMouseClicked
        // muda da aba de tabela de pesquisa para a aba de cadastro
        telaTreinadores.setSelectedIndex(0);
        txtAdversario.setText(tabelaBatalha.getValueAt(tabelaBatalha.getSelectedRow(), 0).toString());
        txtCpf.setText(tabelaBatalha.getValueAt(tabelaBatalha.getSelectedRow(), 1).toString());
        txtEndereco.setText(tabelaBatalha.getValueAt(tabelaBatalha.getSelectedRow(), 2).toString());
        boxStatus.setSelectedItem(tabelaBatalha.getValueAt(tabelaBatalha.getSelectedRow(), 3).toString());
        txtVencedor.setText(tabelaBatalha.getValueAt(tabelaBatalha.getSelectedRow(), 4).toString());
    }//GEN-LAST:event_tabelaBatalhaMouseClicked

    private void buttonNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNewActionPerformed
        //Botao novo
        new PokedexUtil().limpa_dados(this.abaCadastro);
        telaTreinadores.setSelectedIndex(0);
    }//GEN-LAST:event_buttonNewActionPerformed

    private void buttonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveActionPerformed
        //botão de salvar
        Batalha batalha = new Batalha();

        batalha.setEnderecoGinasio(txtEndereco.getText());
        batalha.setCpfTreinador(txtCpf.getText());
        batalha.setAdversario(txtAdversario.getText());
        batalha.setStatus(boxStatus.getSelectedItem().toString());
        batalha.setVencedor(txtVencedor.getText());

        BatalhaDAO dao = new BatalhaDAO();
        dao.cadastrar_batalha(batalha);

        new PokedexUtil().limpa_dados(abaCadastro);
    }//GEN-LAST:event_buttonSaveActionPerformed

    private void buttonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditActionPerformed
        //botao de editar
        Batalha batalha = new Batalha();

        batalha.setEnderecoGinasio(txtEndereco.getText());
        batalha.setCpfTreinador(txtCpf.getText());
        batalha.setAdversario(txtAdversario.getText());
        batalha.setStatus(boxStatus.getSelectedItem().toString());
        batalha.setVencedor(txtVencedor.getText());

        BatalhaDAO dao = new BatalhaDAO();
        dao.alterar_batalha(batalha);

        new PokedexUtil().limpa_dados(abaCadastro);
    }//GEN-LAST:event_buttonEditActionPerformed

    private void boxStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxStatusActionPerformed

    private void txtCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCpfActionPerformed

    private void txtVencedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVencedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVencedorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BatalhaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BatalhaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BatalhaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BatalhaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BatalhaForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel abaCadastro;
    private javax.swing.JPanel abaPesquisa;
    private javax.swing.JComboBox<String> boxStatus;
    private javax.swing.JButton buttonEdit;
    private javax.swing.JButton buttonNew;
    private javax.swing.JButton buttonSave;
    private javax.swing.JButton buttonSearch;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaBatalha;
    private javax.swing.JTabbedPane telaTreinadores;
    private javax.swing.JTextField txtAdversario;
    private javax.swing.JFormattedTextField txtCpf;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtPesquisa;
    private javax.swing.JTextField txtVencedor;
    // End of variables declaration//GEN-END:variables
}
