/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.pokedex.view;

import br.com.pokedex.dao.GinasioDAO;
import br.com.pokedex.model.Ginasio;
import br.com.pokedex.model.PokedexUtil;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;

import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nanda
 */
public class GinasioForm extends javax.swing.JFrame {

    // Metodo listar na tabela
    public void listar_ginasio() {

        GinasioDAO dao = new GinasioDAO();
        List<Ginasio> ginasioList = dao.listar_ginasios();
        DefaultTableModel dados = (DefaultTableModel) tabelaGinasio.getModel();
        dados.setNumRows(0);

        for (Ginasio g : ginasioList) {
            dados.addRow(new Object[]{
                g.getNome(),
                g.getTipo(),
                g.getEndereco()
            });
        }
    }

    /**
     * Creates new form TreinadorForm
     */
    public GinasioForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon = new ImageIcon(getClass().getResource("/images/GinasioDir.png"));
        Image image = icon.getImage();
        jDesktopPane1 = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){
                g.drawImage(image, 0, 0, 900, 550, this);
            }
        };
        telaTreinadores = new javax.swing.JTabbedPane();
        abaCadastro = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtTipo = new javax.swing.JTextField();
        abaPesquisa = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtPesquisa = new javax.swing.JTextField();
        buttonSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaGinasio = new javax.swing.JTable();
        buttonNew = new javax.swing.JButton();
        buttonSave = new javax.swing.JButton();
        buttonEdit = new javax.swing.JButton();
        buttorDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jDesktopPane1.setPreferredSize(new java.awt.Dimension(900, 544));

        telaTreinadores.setBackground(new java.awt.Color(122, 122, 122));
        telaTreinadores.setForeground(new java.awt.Color(0, 0, 0));
        telaTreinadores.setFont(new java.awt.Font("NATS", 0, 16));
        telaTreinadores.setPreferredSize(new java.awt.Dimension(867, 274));

        abaCadastro.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("NATS", 0, 16));
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nome:");

        txtNome.setBackground(new java.awt.Color(255, 255, 255));
        txtNome.setFont(new java.awt.Font("NATS", 0, 16));
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("NATS", 0, 16));
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Endereço:");

        txtEndereco.setBackground(new java.awt.Color(255, 255, 255));
        txtEndereco.setFont(new java.awt.Font("NATS", 0, 16));
        txtEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnderecoActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("NATS", 0, 16));
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Tipo:");

        txtTipo.setBackground(new java.awt.Color(255, 255, 255));
        txtTipo.setFont(new java.awt.Font("NATS", 0, 16));
        txtTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout abaCadastroLayout = new javax.swing.GroupLayout(abaCadastro);
        abaCadastro.setLayout(abaCadastroLayout);
        abaCadastroLayout.setHorizontalGroup(
            abaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaCadastroLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(abaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(abaCadastroLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(abaCadastroLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        abaCadastroLayout.setVerticalGroup(
            abaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaCadastroLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(abaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(abaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(157, Short.MAX_VALUE))
        );

        telaTreinadores.addTab("Dados cadastrais", abaCadastro);

        abaPesquisa.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("NATS", 0, 16));
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nome:");

        txtPesquisa.setBackground(new java.awt.Color(255, 255, 255));
        txtPesquisa.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        txtPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisaActionPerformed(evt);
            }
        });
        txtPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPesquisaKeyPressed(evt);
            }
        });

        buttonSearch.setBackground(new java.awt.Color(153, 153, 153));
        buttonSearch.setFont(new java.awt.Font("NATS", 0, 16));
        buttonSearch.setForeground(new java.awt.Color(0, 0, 0));
        buttonSearch.setText("Pesquisar");
        buttonSearch.setBorderPainted(false);
        buttonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSearchActionPerformed(evt);
            }
        });

        tabelaGinasio.setFont(new java.awt.Font("NATS", 0, 16));
        tabelaGinasio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Tipo", "Endereço"
            }
        ));
        tabelaGinasio.setSelectionBackground(new java.awt.Color(117, 117, 117));
        tabelaGinasio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaGinasioMouseClicked(evt);
            }
        });
        tabelaGinasio.getTableHeader().setFont(new java.awt.Font("NATS", 0, 16));
        tabelaGinasio.getTableHeader().setPreferredSize(new Dimension(50, 30));
        tabelaGinasio.getTableHeader().setBackground(new java.awt.Color(60,63,65));
        jScrollPane1.setViewportView(tabelaGinasio);
        tabelaGinasio.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout abaPesquisaLayout = new javax.swing.GroupLayout(abaPesquisa);
        abaPesquisa.setLayout(abaPesquisaLayout);
        abaPesquisaLayout.setHorizontalGroup(
            abaPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaPesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(382, Short.MAX_VALUE))
            .addGroup(abaPesquisaLayout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        abaPesquisaLayout.setVerticalGroup(
            abaPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaPesquisaLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(abaPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE))
        );

        telaTreinadores.addTab("Pesquisar", abaPesquisa);

        buttonNew.setBackground(new java.awt.Color(153, 153, 153));
        buttonNew.setFont(new java.awt.Font("NATS", 0, 16));
        buttonNew.setForeground(new java.awt.Color(0, 0, 0));
        buttonNew.setText("Novo");
        buttonNew.setBorder(null);
        buttonNew.setBorderPainted(false);
        buttonNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNewActionPerformed(evt);
            }
        });

        buttonSave.setBackground(new java.awt.Color(153, 153, 153));
        buttonSave.setFont(new java.awt.Font("NATS", 0, 16));
        buttonSave.setForeground(new java.awt.Color(0, 0, 0));
        buttonSave.setText("Criar");
        buttonSave.setBorderPainted(false);
        buttonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveActionPerformed(evt);
            }
        });

        buttonEdit.setBackground(new java.awt.Color(153, 153, 153));
        buttonEdit.setFont(new java.awt.Font("NATS", 0, 16));
        buttonEdit.setForeground(new java.awt.Color(0, 0, 0));
        buttonEdit.setText("Salvar");
        buttonEdit.setBorderPainted(false);
        buttonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditActionPerformed(evt);
            }
        });

        buttorDelete.setBackground(new java.awt.Color(153, 153, 153));
        buttorDelete.setFont(new java.awt.Font("NATS", 0, 16));
        buttorDelete.setForeground(new java.awt.Color(0, 0, 0));
        buttorDelete.setText("Excluir");
        buttorDelete.setBorderPainted(false);
        buttorDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttorDeleteActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(telaTreinadores, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(buttonNew, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(buttonSave, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(buttonEdit, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(buttorDelete, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(telaTreinadores, javax.swing.GroupLayout.PREFERRED_SIZE, 867, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(284, 284, 284)
                        .addComponent(buttonNew, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttorDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jDesktopPane1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {buttonEdit, buttonNew, buttonSave, buttorDelete});

        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(telaTreinadores, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                .addGap(81, 81, 81)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buttonSave)
                        .addComponent(buttonEdit)
                        .addComponent(buttorDelete))
                    .addComponent(buttonNew, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83))
        );

        jDesktopPane1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {buttonEdit, buttonNew, buttonSave, buttorDelete});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // Carrega a lista
        listar_ginasio();
    }//GEN-LAST:event_formWindowActivated

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnderecoActionPerformed

    private void txtPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisaActionPerformed

    private void txtPesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaKeyPressed
        //Pesquisa ao digitar
        //Pesquisar treinador por nome
        String nome = "%" + txtPesquisa.getText() + "%";

        GinasioDAO dao = new GinasioDAO();
        List<Ginasio> ginasioList = dao.buscar_ginasio_Nome(nome);
        DefaultTableModel dados = (DefaultTableModel) tabelaGinasio.getModel();
        dados.setNumRows(0);

        for (Ginasio g : ginasioList) {
            dados.addRow(new Object[]{
                g.getNome(),
                g.getTipo(),
                g.getEndereco()
            });
        }
    }//GEN-LAST:event_txtPesquisaKeyPressed

    private void buttonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSearchActionPerformed
        //Pesquisar treinador por nome
        String nome = "%" + txtPesquisa.getText() + "%";

        GinasioDAO dao = new GinasioDAO();
        List<Ginasio> ginasioList = dao.buscar_ginasio_Nome(nome);
        DefaultTableModel dados = (DefaultTableModel) tabelaGinasio.getModel();
        dados.setNumRows(0);

        for (Ginasio g : ginasioList) {
            dados.addRow(new Object[]{
                g.getNome(),
                g.getTipo(),
                g.getEndereco()
            });
        }
    }//GEN-LAST:event_buttonSearchActionPerformed

    private void tabelaGinasioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaGinasioMouseClicked
        // muda da aba de tabela de pesquisa para a aba de cadastro
        telaTreinadores.setSelectedIndex(0);
        txtNome.setText(tabelaGinasio.getValueAt(tabelaGinasio.getSelectedRow(), 0).toString());
        txtTipo.setText(tabelaGinasio.getValueAt(tabelaGinasio.getSelectedRow(), 1).toString());
        txtEndereco.setText(tabelaGinasio.getValueAt(tabelaGinasio.getSelectedRow(), 2).toString());
    }//GEN-LAST:event_tabelaGinasioMouseClicked

    private void buttonNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNewActionPerformed
        //Botao novo
        new PokedexUtil().limpa_dados(this.abaCadastro);
        telaTreinadores.setSelectedIndex(0);
    }//GEN-LAST:event_buttonNewActionPerformed

    private void buttonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveActionPerformed
        //botão de salvar
        Ginasio ginasio = new Ginasio();

        ginasio.setNome(txtNome.getText());
        ginasio.setTipo(txtTipo.getText());
        ginasio.setEndereco(txtEndereco.getText());

        GinasioDAO dao = new GinasioDAO();
        dao.cadastrar_ginasio(ginasio);

        new PokedexUtil().limpa_dados(abaCadastro);
    }//GEN-LAST:event_buttonSaveActionPerformed

    private void buttonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditActionPerformed
        //botao de editar
        Ginasio ginasio = new Ginasio();

        ginasio.setNome(txtNome.getText());
        ginasio.setTipo(txtTipo.getText());
        ginasio.setEndereco(txtEndereco.getText());

        GinasioDAO dao = new GinasioDAO();
        dao.alterar_ginasio(ginasio);

        new PokedexUtil().limpa_dados(abaCadastro);
    }//GEN-LAST:event_buttonEditActionPerformed

    private void buttorDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttorDeleteActionPerformed
        //botao excluir
        Ginasio ginasio = new Ginasio();

        ginasio.setNome(txtNome.getText());
        ginasio.setEndereco(txtEndereco.getText());

        GinasioDAO dao = new GinasioDAO();
        dao.excluir_ginasio(ginasio);

        new PokedexUtil().limpa_dados(abaCadastro);
    }//GEN-LAST:event_buttorDeleteActionPerformed

    private void txtTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GinasioForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GinasioForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GinasioForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GinasioForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GinasioForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel abaCadastro;
    private javax.swing.JPanel abaPesquisa;
    private javax.swing.JButton buttonEdit;
    private javax.swing.JButton buttonNew;
    private javax.swing.JButton buttonSave;
    private javax.swing.JButton buttonSearch;
    private javax.swing.JButton buttorDelete;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaGinasio;
    private javax.swing.JTabbedPane telaTreinadores;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPesquisa;
    private javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables
}
