/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.pokedex.view;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author nanda
 */
public class MenuForm extends javax.swing.JFrame {

    /**
     * Creates new form MenuForm
     */
    public MenuForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon = new ImageIcon(getClass().getResource("/images/telaMenuNova.png"));
        Image image = icon.getImage();
        jDesktopPane1 = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){
                g.drawImage(image, 0, 0, 720, 512, this);
            }
        };
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuPokemons = new javax.swing.JMenu();
        MenuAcessoPokemons = new javax.swing.JMenuItem();
        MenuTreinadores = new javax.swing.JMenu();
        MenuAcessoTreinadores = new javax.swing.JMenuItem();
        MenuGinasios = new javax.swing.JMenu();
        MenuAcessoGinasios = new javax.swing.JMenuItem();
        MenuBatalhas = new javax.swing.JMenu();
        MenuAcessoBatalhas = new javax.swing.JMenuItem();
        MenuMudarUsuario = new javax.swing.JMenu();
        MenuTrocarUsuario = new javax.swing.JMenuItem();
        MenuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 512, Short.MAX_VALUE)
        );

        jMenuBar1.setForeground(new java.awt.Color(196, 196, 196));
        jMenuBar1.setAutoscrolls(true);

        MenuPokemons.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pikachuAjustado.png"))); // NOI18N
        MenuPokemons.setText("Pokémons");
        MenuPokemons.setFont(new java.awt.Font("NATS", 0, 18));

        MenuAcessoPokemons.setFont(new java.awt.Font("NATS", 0, 16));
        MenuAcessoPokemons.setText("Acesso aos Pokémons");
        MenuAcessoPokemons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAcessoPokemonsActionPerformed(evt);
            }
        });
        MenuPokemons.add(MenuAcessoPokemons);

        jMenuBar1.add(MenuPokemons);

        MenuTreinadores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/treinadorAjustado.png"))); // NOI18N
        MenuTreinadores.setText("Treinadores");
        MenuTreinadores.setFont(new java.awt.Font("NATS", 0, 18));

        MenuAcessoTreinadores.setFont(new java.awt.Font("NATS", 0, 16));
        MenuAcessoTreinadores.setText("Acesso aos Treinadores");
        MenuAcessoTreinadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAcessoTreinadoresActionPerformed(evt);
            }
        });
        MenuTreinadores.add(MenuAcessoTreinadores);

        jMenuBar1.add(MenuTreinadores);

        MenuGinasios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mapaAjustado.png"))); // NOI18N
        MenuGinasios.setText("Ginásios");
        MenuGinasios.setFont(new java.awt.Font("NATS", 0, 18));

        MenuAcessoGinasios.setFont(new java.awt.Font("NATS", 0, 16));
        MenuAcessoGinasios.setText("Acesso aos Ginásios");
        MenuAcessoGinasios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAcessoGinasiosActionPerformed(evt);
            }
        });
        MenuGinasios.add(MenuAcessoGinasios);

        jMenuBar1.add(MenuGinasios);

        MenuBatalhas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/batalhaAjustado.png"))); // NOI18N
        MenuBatalhas.setText("Batalhas");
        MenuBatalhas.setFont(new java.awt.Font("NATS", 0, 18));

        MenuAcessoBatalhas.setFont(new java.awt.Font("NATS", 0, 16));
        MenuAcessoBatalhas.setText("Acesso às Batalhas");
        MenuAcessoBatalhas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAcessoBatalhasActionPerformed(evt);
            }
        });
        MenuBatalhas.add(MenuAcessoBatalhas);

        jMenuBar1.add(MenuBatalhas);

        MenuMudarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/configuracaoAjustado.png"))); // NOI18N
        MenuMudarUsuario.setText("Configurações");
        MenuMudarUsuario.setFont(new java.awt.Font("NATS", 0, 18));

        MenuTrocarUsuario.setFont(new java.awt.Font("NATS", 0, 16));
        MenuTrocarUsuario.setText("Trocar de Usuário");
        MenuTrocarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuTrocarUsuarioActionPerformed(evt);
            }
        });
        MenuMudarUsuario.add(MenuTrocarUsuario);

        jMenuBar1.add(MenuMudarUsuario);

        MenuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sairAjustado.png"))); // NOI18N
        MenuSair.setText("Sair");
        MenuSair.setFont(new java.awt.Font("NATS", 0, 18));
        MenuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuSairMouseClicked(evt);
            }
        });
        jMenuBar1.add(MenuSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MenuTrocarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuTrocarUsuarioActionPerformed
        // Trocar de usuario
        LoginForm login = new LoginForm();
        this.dispose();
        login.setVisible(true);
    }//GEN-LAST:event_MenuTrocarUsuarioActionPerformed

    private void MenuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuSairMouseClicked
        // Sair
        int op;
        op = JOptionPane.showConfirmDialog(null, "Deseja sair?");
        if(op == 0){
            System.exit(0);
        }
    }//GEN-LAST:event_MenuSairMouseClicked

    private void MenuAcessoPokemonsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAcessoPokemonsActionPerformed
        //Acesso ao menu de pokemons
        PokemonForm menuPokemons = new PokemonForm();
        menuPokemons.setVisible(true);
    }//GEN-LAST:event_MenuAcessoPokemonsActionPerformed

    private void MenuAcessoTreinadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAcessoTreinadoresActionPerformed
        // TODO add your handling code here:
        TreinadorForm menuTreinadores = new TreinadorForm();
        menuTreinadores.setVisible(true);
    }//GEN-LAST:event_MenuAcessoTreinadoresActionPerformed

    private void MenuAcessoGinasiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAcessoGinasiosActionPerformed
        // TODO add your handling code here:
        GinasioForm menuGinasios = new GinasioForm();
        menuGinasios.setVisible(true);
    }//GEN-LAST:event_MenuAcessoGinasiosActionPerformed

    private void MenuAcessoBatalhasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAcessoBatalhasActionPerformed
        // TODO add your handling code here:
        BatalhaForm menuBatalha = new BatalhaForm();
        menuBatalha.setVisible(true);
    }//GEN-LAST:event_MenuAcessoBatalhasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuAcessoBatalhas;
    private javax.swing.JMenuItem MenuAcessoGinasios;
    private javax.swing.JMenuItem MenuAcessoPokemons;
    private javax.swing.JMenuItem MenuAcessoTreinadores;
    public javax.swing.JMenu MenuBatalhas;
    public javax.swing.JMenu MenuGinasios;
    private javax.swing.JMenu MenuMudarUsuario;
    public javax.swing.JMenu MenuPokemons;
    private javax.swing.JMenu MenuSair;
    public javax.swing.JMenu MenuTreinadores;
    private javax.swing.JMenuItem MenuTrocarUsuario;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
