/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.pokedex.view;

import br.com.pokedex.dao.PokemonDAO;
import br.com.pokedex.model.PokedexUtil;
import br.com.pokedex.model.Pokemon;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nanda
 */
public class PokemonForm extends javax.swing.JFrame {

    // Metodo listar na tabela
    public void listar_pokemon(){
        
        PokemonDAO dao = new PokemonDAO();
        List<Pokemon> pokemonList = dao.listar_pokemons();
        DefaultTableModel dados = (DefaultTableModel) tabelaPokemon.getModel();
        dados.setNumRows(0);
        
        for(Pokemon p : pokemonList){
            dados.addRow(new Object[]{
                p.getId(),
                p.getNome(),
                p.getTipo(),
                p.getPontosCombate(),
                p.getLocalCaptura(),
                p.getDataCaptura(),
                p.getEvolucao(),
                p.getCpfTreinador()
            });
        }
    }
    
    /**
     * Creates new form TreinadorForm
     */
    public PokemonForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon = new ImageIcon(getClass().getResource("/images/PokemonDir.png"));
        Image image = icon.getImage();
        jDesktopPane1 = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){
                g.drawImage(image, 0, 0, 900, 550, this);
            }
        };
        telaPokemon = new javax.swing.JTabbedPane();
        abaCadastro = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtTipo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtDataCaptura = new javax.swing.JFormattedTextField();
        jLabel17 = new javax.swing.JLabel();
        txtPontosCombate = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtLocalCaptura = new javax.swing.JTextField();
        txtEvolucao = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtCpfTreinador = new javax.swing.JFormattedTextField();
        abaPesquisa = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtPesquisa = new javax.swing.JTextField();
        buttonSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaPokemon = new javax.swing.JTable();
        buttonNew = new javax.swing.JButton();
        buttonSave = new javax.swing.JButton();
        buttonEdit = new javax.swing.JButton();
        buttorDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jDesktopPane1.setPreferredSize(new java.awt.Dimension(900, 550));

        telaPokemon.setFont(new java.awt.Font("NATS", 0, 16));
        telaPokemon.setPreferredSize(new java.awt.Dimension(900, 350));

        abaCadastro.setBackground(new java.awt.Color(255, 255, 255));
        abaCadastro.setPreferredSize(new java.awt.Dimension(900, 350));

        jLabel2.setFont(new java.awt.Font("NATS", 0, 16));
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nome:");

        txtNome.setBackground(new java.awt.Color(255, 255, 255));
        txtNome.setFont(new java.awt.Font("NATS", 0, 16));
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        txtTipo.setBackground(new java.awt.Color(255, 255, 255));
        txtTipo.setFont(new java.awt.Font("NATS", 0, 16));
        txtTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("NATS", 0, 16));
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Tipo:");

        jLabel14.setFont(new java.awt.Font("NATS", 0, 16));
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Data de captura:");

        txtDataCaptura.setBackground(new java.awt.Color(255, 255, 255));
        try {
            txtDataCaptura.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataCaptura.setFont(new java.awt.Font("NATS", 0, 16));
        txtDataCaptura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataCapturaActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("NATS", 0, 16));
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Pontos de combate:");

        txtPontosCombate.setBackground(new java.awt.Color(255, 255, 255));
        txtPontosCombate.setFont(new java.awt.Font("NATS", 0, 16));
        txtPontosCombate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPontosCombateActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("NATS", 0, 16));
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("ID:");

        txtID.setEditable(false);
        txtID.setBackground(new java.awt.Color(255, 255, 255));
        txtID.setFont(new java.awt.Font("NATS", 0, 16));
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("NATS", 0, 16));
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Local de captura:");

        txtLocalCaptura.setBackground(new java.awt.Color(255, 255, 255));
        txtLocalCaptura.setFont(new java.awt.Font("NATS", 0, 16));
        txtLocalCaptura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLocalCapturaActionPerformed(evt);
            }
        });

        txtEvolucao.setBackground(new java.awt.Color(255, 255, 255));
        txtEvolucao.setFont(new java.awt.Font("NATS", 0, 16));
        txtEvolucao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEvolucaoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("NATS", 0, 16));
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Evolução:");

        jLabel18.setFont(new java.awt.Font("NATS", 0, 16));
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("CPF Treinador:");

        txtCpfTreinador.setBackground(new java.awt.Color(255, 255, 255));
        try {
            txtCpfTreinador.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpfTreinador.setFont(new java.awt.Font("NATS", 0, 16));
        txtCpfTreinador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCpfTreinadorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout abaCadastroLayout = new javax.swing.GroupLayout(abaCadastro);
        abaCadastro.setLayout(abaCadastroLayout);
        abaCadastroLayout.setHorizontalGroup(
            abaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaCadastroLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(abaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(abaCadastroLayout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(abaCadastroLayout.createSequentialGroup()
                        .addGroup(abaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(abaCadastroLayout.createSequentialGroup()
                                .addGroup(abaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(abaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(abaCadastroLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNome))
                                    .addGroup(abaCadastroLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(abaCadastroLayout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtLocalCaptura, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(abaCadastroLayout.createSequentialGroup()
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCpfTreinador, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(43, 43, 43)
                        .addGroup(abaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, abaCadastroLayout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPontosCombate, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(abaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(abaCadastroLayout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtDataCaptura, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(abaCadastroLayout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtEvolucao, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        abaCadastroLayout.setVerticalGroup(
            abaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(abaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(abaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(txtPontosCombate, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(abaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtEvolucao, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(abaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtLocalCaptura, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(txtDataCaptura, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(abaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtCpfTreinador, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(111, Short.MAX_VALUE))
        );

        telaPokemon.addTab("Dados cadastrais", abaCadastro);

        abaPesquisa.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("NATS", 0, 16));
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nome:");

        txtPesquisa.setBackground(new java.awt.Color(255, 255, 255));
        txtPesquisa.setFont(new java.awt.Font("NATS", 0, 16));
        txtPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisaActionPerformed(evt);
            }
        });
        txtPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPesquisaKeyPressed(evt);
            }
        });

        buttonSearch.setBackground(new java.awt.Color(153, 153, 153));
        buttonSearch.setFont(new java.awt.Font("NATS", 0, 16));
        buttonSearch.setForeground(new java.awt.Color(0, 0, 0));
        buttonSearch.setText("Pesquisar");
        buttonSearch.setBorderPainted(false);
        buttonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSearchActionPerformed(evt);
            }
        });

        tabelaPokemon.setFont(new java.awt.Font("NATS", 0, 16));
        tabelaPokemon.getTableHeader().setFont(new java.awt.Font("NATS", 0, 16));
        tabelaPokemon.getTableHeader().setPreferredSize(new Dimension(50, 30));
        tabelaPokemon.getTableHeader().setBackground(new java.awt.Color(60,63,65));
        tabelaPokemon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Tipo", "PC", "Local de captura", "Data de captura", "Evolução", "Treinador"
            }
        ));
        tabelaPokemon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaPokemonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaPokemon);

        javax.swing.GroupLayout abaPesquisaLayout = new javax.swing.GroupLayout(abaPesquisa);
        abaPesquisa.setLayout(abaPesquisaLayout);
        abaPesquisaLayout.setHorizontalGroup(
            abaPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaPesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(395, Short.MAX_VALUE))
            .addGroup(abaPesquisaLayout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        abaPesquisaLayout.setVerticalGroup(
            abaPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaPesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(abaPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE))
        );

        telaPokemon.addTab("Pesquisar", abaPesquisa);

        buttonNew.setBackground(new java.awt.Color(153, 153, 153));
        buttonNew.setFont(new java.awt.Font("NATS", 0, 16));
        buttonNew.setForeground(new java.awt.Color(0, 0, 0));
        buttonNew.setText("Novo");
        buttonNew.setBorderPainted(false);
        buttonNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNewActionPerformed(evt);
            }
        });

        buttonSave.setBackground(new java.awt.Color(153, 153, 153));
        buttonSave.setFont(new java.awt.Font("NATS", 0, 16));
        buttonSave.setForeground(new java.awt.Color(0, 0, 0));
        buttonSave.setText("Criar");
        buttonSave.setBorderPainted(false);
        buttonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveActionPerformed(evt);
            }
        });

        buttonEdit.setBackground(new java.awt.Color(153, 153, 153));
        buttonEdit.setFont(new java.awt.Font("NATS", 0, 16));
        buttonEdit.setForeground(new java.awt.Color(0, 0, 0));
        buttonEdit.setText("Salvar");
        buttonEdit.setBorderPainted(false);
        buttonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditActionPerformed(evt);
            }
        });

        buttorDelete.setBackground(new java.awt.Color(153, 153, 153));
        buttorDelete.setFont(new java.awt.Font("NATS", 0, 16));
        buttorDelete.setForeground(new java.awt.Color(0, 0, 0));
        buttorDelete.setText("Excluir");
        buttorDelete.setBorderPainted(false);
        buttorDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttorDeleteActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(telaPokemon, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(buttonNew, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(buttonSave, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(buttonEdit, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(buttorDelete, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonNew, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttorDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(280, 280, 280))
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(telaPokemon, javax.swing.GroupLayout.PREFERRED_SIZE, 880, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jDesktopPane1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {buttonEdit, buttonNew, buttonSave, buttorDelete});

        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addComponent(telaPokemon, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buttonSave)
                        .addComponent(buttonEdit)
                        .addComponent(buttorDelete))
                    .addComponent(buttonNew))
                .addGap(61, 61, 61))
        );

        jDesktopPane1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {buttonEdit, buttonNew, buttonSave, buttorDelete});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // Carrega a lista
        listar_pokemon();
    }//GEN-LAST:event_formWindowActivated

    private void buttorDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttorDeleteActionPerformed
        //botao excluir
        Pokemon pokemon = new Pokemon();

        pokemon.setId(Integer.parseInt(txtID.getText()));

        PokemonDAO dao = new PokemonDAO();
        dao.excluir_pokemon(pokemon);

        new PokedexUtil().limpa_dados(abaCadastro);
    }//GEN-LAST:event_buttorDeleteActionPerformed

    private void buttonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditActionPerformed
        //botao de editar
        Pokemon pokemon = new Pokemon();

        pokemon.setId(Integer.parseInt(txtID.getText()));
        pokemon.setNome(txtNome.getText());
        pokemon.setTipo(txtTipo.getText());
        pokemon.setPontosCombate(Integer.parseInt(txtPontosCombate.getText()));
        pokemon.setLocalCaptura(txtLocalCaptura.getText());
        pokemon.setDataCaptura(txtDataCaptura.getText());
        pokemon.setEvolucao(txtEvolucao.getText());
        pokemon.setCpfTreinador(txtCpfTreinador.getText());

        PokemonDAO dao = new PokemonDAO();
        dao.alterar_pokemon(pokemon);

        new PokedexUtil().limpa_dados(abaCadastro);
    }//GEN-LAST:event_buttonEditActionPerformed

    private void buttonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveActionPerformed
        //botão de salvar
        Pokemon pokemon = new Pokemon();
        
        pokemon.setNome(txtNome.getText());
        pokemon.setTipo(txtTipo.getText());
        pokemon.setPontosCombate(Integer.parseInt(txtPontosCombate.getText()));
        pokemon.setLocalCaptura(txtLocalCaptura.getText());
        pokemon.setDataCaptura(txtDataCaptura.getText());
        pokemon.setEvolucao(txtEvolucao.getText());
        pokemon.setCpfTreinador(txtCpfTreinador.getText());

        PokemonDAO dao = new PokemonDAO();
        dao.cadastrar_pokemon(pokemon);

        new PokedexUtil().limpa_dados(this.abaCadastro);
    }//GEN-LAST:event_buttonSaveActionPerformed

    private void buttonNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNewActionPerformed
        //Botao novo
        new PokedexUtil().limpa_dados(this.abaCadastro);
        telaPokemon.setSelectedIndex(0);
    }//GEN-LAST:event_buttonNewActionPerformed

    private void tabelaPokemonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaPokemonMouseClicked
        // muda da aba de tabela de pesquisa para a aba de cadastro
        telaPokemon.setSelectedIndex(0);
        txtID.setText(tabelaPokemon.getValueAt(tabelaPokemon.getSelectedRow(), 0).toString());
        txtNome.setText(tabelaPokemon.getValueAt(tabelaPokemon.getSelectedRow(), 1).toString());
        txtTipo.setText(tabelaPokemon.getValueAt(tabelaPokemon.getSelectedRow(), 2).toString());
        txtPontosCombate.setText(tabelaPokemon.getValueAt(tabelaPokemon.getSelectedRow(), 3).toString());
        txtLocalCaptura.setText(tabelaPokemon.getValueAt(tabelaPokemon.getSelectedRow(), 4).toString());
        txtDataCaptura.setText(tabelaPokemon.getValueAt(tabelaPokemon.getSelectedRow(), 5).toString());
        txtEvolucao.setText(tabelaPokemon.getValueAt(tabelaPokemon.getSelectedRow(), 6).toString());
        txtCpfTreinador.setText(tabelaPokemon.getValueAt(tabelaPokemon.getSelectedRow(), 7).toString());
        
    }//GEN-LAST:event_tabelaPokemonMouseClicked

    private void buttonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSearchActionPerformed
        //Pesquisar pokemon por nome
        String nome = "%" + txtPesquisa.getText() + "%";

        PokemonDAO dao = new PokemonDAO();
        List<Pokemon> pokemonList = dao.buscar_pokemon_Nome(nome);
        DefaultTableModel dados = (DefaultTableModel) tabelaPokemon.getModel();
        dados.setNumRows(0);

        for(Pokemon p : pokemonList){
            dados.addRow(new Object[]{
                p.getId(),
                p.getNome(),
                p.getTipo(),
                p.getPontosCombate(),
                p.getLocalCaptura(),
                p.getDataCaptura(),
                p.getEvolucao(),
                p.getCpfTreinador()
            });
        }

    }//GEN-LAST:event_buttonSearchActionPerformed

    private void txtPesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaKeyPressed
        //Pesquisa ao digitar
        //Pesquisar pokemon por nome
        String nome = "%" + txtPesquisa.getText() + "%";

        PokemonDAO dao = new PokemonDAO();
        List<Pokemon> pokemonList = dao.buscar_pokemon_Nome(nome);
        DefaultTableModel dados = (DefaultTableModel) tabelaPokemon.getModel();
        dados.setNumRows(0);

        for(Pokemon p : pokemonList){
            dados.addRow(new Object[]{
                p.getId(),
                p.getNome(),
                p.getTipo(),
                p.getPontosCombate(),
                p.getLocalCaptura(),
                p.getDataCaptura(),
                p.getEvolucao(),
                p.getCpfTreinador()
            });
        }
    }//GEN-LAST:event_txtPesquisaKeyPressed

    private void txtPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisaActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void txtPontosCombateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPontosCombateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPontosCombateActionPerformed

    private void txtDataCapturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataCapturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataCapturaActionPerformed

    private void txtTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipoActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtLocalCapturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLocalCapturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLocalCapturaActionPerformed

    private void txtEvolucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEvolucaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEvolucaoActionPerformed

    private void txtCpfTreinadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpfTreinadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCpfTreinadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PokemonForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PokemonForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PokemonForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PokemonForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PokemonForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel abaCadastro;
    private javax.swing.JPanel abaPesquisa;
    private javax.swing.JButton buttonEdit;
    private javax.swing.JButton buttonNew;
    private javax.swing.JButton buttonSave;
    private javax.swing.JButton buttonSearch;
    private javax.swing.JButton buttorDelete;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaPokemon;
    private javax.swing.JTabbedPane telaPokemon;
    private javax.swing.JFormattedTextField txtCpfTreinador;
    private javax.swing.JFormattedTextField txtDataCaptura;
    private javax.swing.JTextField txtEvolucao;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtLocalCaptura;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPesquisa;
    private javax.swing.JTextField txtPontosCombate;
    private javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables
}
