/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.pokedex.view;

import br.com.pokedex.dao.PokemonDAO;
import br.com.pokedex.model.PokedexUtil;
import br.com.pokedex.model.Pokemon;
import java.awt.Graphics;
import java.awt.Image;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nanda
 */
public class PokemonForm extends javax.swing.JFrame {

    private int id = 0;
    // Metodo listar na tabela
    public void listar_pokemon(){
        
        PokemonDAO dao = new PokemonDAO();
        List<Pokemon> pokemonList = dao.listar_pokemons();
        DefaultTableModel dados = (DefaultTableModel) tabelaPokemon.getModel();
        dados.setNumRows(0);
        
        for(Pokemon p : pokemonList){
            dados.addRow(new Object[]{
                p.getId(),
                p.getNome(),
                p.getTipo(),
                p.getPontosCombate(),
                p.getDataCaptura(),
                p.getBatalhasVencidas(),
                p.getBatalhasPerdidas(),
                p.getPossuiEvolucao(),
                p.getPodeEvoluir(),
                p.getStatusBatalha()
            });
        }
    }
    
    /**
     * Creates new form TreinadorForm
     */
    public PokemonForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon = new ImageIcon(getClass().getResource("/images/telaFundoPokemons.png"));
        Image image = icon.getImage();
        jDesktopPane1 = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){
                g.drawImage(image, 0, 0, 1080, 768, this);
            }
        };
        telaPokemon = new javax.swing.JTabbedPane();
        abaCadastro = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtTipo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtDataCaptura = new javax.swing.JFormattedTextField();
        jLabel17 = new javax.swing.JLabel();
        txtPontosCombate = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtBatalhasVencidas = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtBatalhasPerdidas = new javax.swing.JTextField();
        checkEmBatalha = new javax.swing.JCheckBox();
        checkPodeEvoluir = new javax.swing.JCheckBox();
        jLabel20 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        checkPossuiEvolucao = new javax.swing.JCheckBox();
        abaPesquisa = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtPesquisa = new javax.swing.JTextField();
        buttonSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaPokemon = new javax.swing.JTable();
        buttonNew = new javax.swing.JButton();
        buttonSave = new javax.swing.JButton();
        buttonEdit = new javax.swing.JButton();
        buttorDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        telaPokemon.setFont(new java.awt.Font("NATS", 0, 18));

        abaCadastro.setBackground(new java.awt.Color(255, 255, 255));
        abaCadastro.setPreferredSize(new java.awt.Dimension(1056, 400));

        jLabel2.setFont(new java.awt.Font("NATS", 0, 18));
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nome:");

        txtNome.setBackground(new java.awt.Color(255, 255, 255));
        txtNome.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        txtTipo.setBackground(new java.awt.Color(255, 255, 255));
        txtTipo.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        txtTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("NATS", 0, 18));
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Tipo:");

        jLabel14.setFont(new java.awt.Font("NATS", 0, 18));
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Data de captura:");

        txtDataCaptura.setBackground(new java.awt.Color(255, 255, 255));
        try {
            txtDataCaptura.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataCaptura.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        txtDataCaptura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataCapturaActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("NATS", 0, 18));
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Pontos de combate:");

        txtPontosCombate.setBackground(new java.awt.Color(255, 255, 255));
        txtPontosCombate.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        txtPontosCombate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPontosCombateActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("NATS", 0, 18));
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Batalhas vencidas:");

        txtBatalhasVencidas.setBackground(new java.awt.Color(255, 255, 255));
        txtBatalhasVencidas.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        txtBatalhasVencidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBatalhasVencidasActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("NATS", 0, 18));
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Batalhas perdidas:");

        txtBatalhasPerdidas.setBackground(new java.awt.Color(255, 255, 255));
        txtBatalhasPerdidas.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        txtBatalhasPerdidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBatalhasPerdidasActionPerformed(evt);
            }
        });

        checkEmBatalha.setBackground(new java.awt.Color(255, 255, 255));
        checkEmBatalha.setFont(new java.awt.Font("NATS", 0, 18));
        checkEmBatalha.setForeground(new java.awt.Color(0, 0, 0));
        checkEmBatalha.setText("Pokémon em batalha");
        checkEmBatalha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkEmBatalhaActionPerformed(evt);
            }
        });

        checkPodeEvoluir.setBackground(new java.awt.Color(255, 255, 255));
        checkPodeEvoluir.setFont(new java.awt.Font("NATS", 0, 18));
        checkPodeEvoluir.setForeground(new java.awt.Color(0, 0, 0));
        checkPodeEvoluir.setText("Pode evoluir");
        checkPodeEvoluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkPodeEvoluirActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("NATS", 0, 18));
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("ID:");

        txtID.setEditable(false);
        txtID.setBackground(new java.awt.Color(255, 255, 255));
        txtID.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });

        checkPossuiEvolucao.setBackground(new java.awt.Color(255, 255, 255));
        checkPossuiEvolucao.setFont(new java.awt.Font("NATS", 0, 18));
        checkPossuiEvolucao.setForeground(new java.awt.Color(0, 0, 0));
        checkPossuiEvolucao.setText("Possui evolução");
        checkPossuiEvolucao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkPossuiEvolucaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout abaCadastroLayout = new javax.swing.GroupLayout(abaCadastro);
        abaCadastro.setLayout(abaCadastroLayout);
        abaCadastroLayout.setHorizontalGroup(
            abaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaCadastroLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(abaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(abaCadastroLayout.createSequentialGroup()
                        .addGroup(abaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(abaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 200, Short.MAX_VALUE)
                        .addGroup(abaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(abaCadastroLayout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPontosCombate, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(abaCadastroLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(abaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(checkPodeEvoluir, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(checkPossuiEvolucao, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(checkEmBatalha, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(135, 135, 135))
                    .addGroup(abaCadastroLayout.createSequentialGroup()
                        .addGroup(abaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(abaCadastroLayout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(abaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(abaCadastroLayout.createSequentialGroup()
                                    .addComponent(jLabel19)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtBatalhasPerdidas, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(abaCadastroLayout.createSequentialGroup()
                                    .addComponent(jLabel18)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtBatalhasVencidas, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(abaCadastroLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDataCaptura, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        abaCadastroLayout.setVerticalGroup(
            abaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(abaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(abaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(abaCadastroLayout.createSequentialGroup()
                        .addGroup(abaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(abaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(abaCadastroLayout.createSequentialGroup()
                        .addGroup(abaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(txtPontosCombate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(abaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkPossuiEvolucao)
                            .addGroup(abaCadastroLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(checkPodeEvoluir)))))
                .addGap(18, 18, 18)
                .addGroup(abaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtBatalhasVencidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(abaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtBatalhasPerdidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(abaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtDataCaptura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkEmBatalha))
                .addContainerGap(142, Short.MAX_VALUE))
        );

        telaPokemon.addTab("Dados cadastrais", abaCadastro);

        abaPesquisa.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nome:");

        txtPesquisa.setBackground(new java.awt.Color(255, 255, 255));
        txtPesquisa.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        txtPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisaActionPerformed(evt);
            }
        });
        txtPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPesquisaKeyPressed(evt);
            }
        });

        buttonSearch.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        buttonSearch.setText("Pesquisar");
        buttonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSearchActionPerformed(evt);
            }
        });

        tabelaPokemon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Tipo", "Pontos de combate", "Data de captura", "Batalhas vencidas", "Batalhas perdidas", "Possui evolução", "Pode evoluir", "Em batalha"
            }
        ));
        tabelaPokemon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaPokemonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaPokemon);

        javax.swing.GroupLayout abaPesquisaLayout = new javax.swing.GroupLayout(abaPesquisa);
        abaPesquisa.setLayout(abaPesquisaLayout);
        abaPesquisaLayout.setHorizontalGroup(
            abaPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaPesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(573, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        abaPesquisaLayout.setVerticalGroup(
            abaPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaPesquisaLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(abaPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE))
        );

        telaPokemon.addTab("Pesquisar", abaPesquisa);

        buttonNew.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        buttonNew.setText("Novo");
        buttonNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNewActionPerformed(evt);
            }
        });

        buttonSave.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        buttonSave.setText("Salvar");
        buttonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveActionPerformed(evt);
            }
        });

        buttonEdit.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        buttonEdit.setText("Editar");
        buttonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditActionPerformed(evt);
            }
        });

        buttorDelete.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        buttorDelete.setText("Excluir");
        buttorDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttorDeleteActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(telaPokemon, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(buttonNew, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(buttonSave, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(buttonEdit, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(buttorDelete, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(telaPokemon, javax.swing.GroupLayout.PREFERRED_SIZE, 1058, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(374, 374, 374)
                .addComponent(buttonNew, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttorDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jDesktopPane1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {buttonEdit, buttonNew, buttonSave, buttorDelete});

        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(telaPokemon, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buttonSave)
                        .addComponent(buttonEdit)
                        .addComponent(buttorDelete))
                    .addComponent(buttonNew))
                .addGap(61, 61, 61))
        );

        jDesktopPane1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {buttonEdit, buttonNew, buttonSave, buttorDelete});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // Carrega a lista
        listar_pokemon();
    }//GEN-LAST:event_formWindowActivated

    private void buttorDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttorDeleteActionPerformed
        //botao excluir
        Pokemon pokemon = new Pokemon();

        pokemon.setId(Integer.parseInt(txtID.getText()));

        PokemonDAO dao = new PokemonDAO();
        dao.excluir_pokemon(pokemon);

        new PokedexUtil().limpa_dados(abaCadastro);
    }//GEN-LAST:event_buttorDeleteActionPerformed

    private void buttonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditActionPerformed
        //botao de editar
        Pokemon pokemon = new Pokemon();

        pokemon.setId(Integer.parseInt(txtID.getText()));
        pokemon.setNome(txtNome.getText());
        pokemon.setTipo(txtTipo.getText());
        pokemon.setPontosCombate(Integer.parseInt(txtPontosCombate.getText()));
        pokemon.setPossuiEvolucao(checkPossuiEvolucao.isSelected());
        pokemon.setStatusBatalha(checkEmBatalha.isSelected());
        pokemon.setPodeEvoluir(checkPodeEvoluir.isSelected());
        pokemon.setDataCaptura(txtDataCaptura.getText());
        pokemon.setBatalhasVencidas(Integer.parseInt(txtBatalhasVencidas.getText()));
        pokemon.setBatalhasPerdidas(Integer.parseInt(txtBatalhasPerdidas.getText()));

        PokemonDAO dao = new PokemonDAO();
        dao.alterar_pokemon(pokemon);

        new PokedexUtil().limpa_dados(abaCadastro);
    }//GEN-LAST:event_buttonEditActionPerformed

    private void buttonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveActionPerformed
        //botão de salvar
        Pokemon pokemon = new Pokemon();

        pokemon.setNome(txtNome.getText());
        pokemon.setTipo(txtTipo.getText());
        pokemon.setPontosCombate(Integer.parseInt(txtPontosCombate.getText()));
        pokemon.setPossuiEvolucao(checkPossuiEvolucao.isSelected());
        pokemon.setStatusBatalha(false);
        pokemon.setPodeEvoluir(false);
        pokemon.setDataCaptura(txtDataCaptura.getText());
        pokemon.setBatalhasVencidas(0);
        pokemon.setBatalhasPerdidas(0);

        PokemonDAO dao = new PokemonDAO();
        dao.cadastrar_pokemon(pokemon);

        new PokedexUtil().limpa_dados(this.abaCadastro);
    }//GEN-LAST:event_buttonSaveActionPerformed

    private void buttonNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNewActionPerformed
        //Botao novo
        new PokedexUtil().limpa_dados(this.abaCadastro);
        telaPokemon.setSelectedIndex(0);
    }//GEN-LAST:event_buttonNewActionPerformed

    private void tabelaPokemonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaPokemonMouseClicked
        // muda da aba de tabela de pesquisa para a aba de cadastro
        telaPokemon.setSelectedIndex(0);
        txtID.setText(tabelaPokemon.getValueAt(tabelaPokemon.getSelectedRow(), 0).toString());
        txtNome.setText(tabelaPokemon.getValueAt(tabelaPokemon.getSelectedRow(), 1).toString());
        txtTipo.setText(tabelaPokemon.getValueAt(tabelaPokemon.getSelectedRow(), 2).toString());
        txtPontosCombate.setText(tabelaPokemon.getValueAt(tabelaPokemon.getSelectedRow(), 3).toString());
        txtDataCaptura.setText(tabelaPokemon.getValueAt(tabelaPokemon.getSelectedRow(), 4).toString());
        txtBatalhasVencidas.setText(tabelaPokemon.getValueAt(tabelaPokemon.getSelectedRow(), 5).toString());
        txtBatalhasPerdidas.setText(tabelaPokemon.getValueAt(tabelaPokemon.getSelectedRow(), 6).toString());
        if(tabelaPokemon.getValueAt(tabelaPokemon.getSelectedRow(), 7).toString() == "true")
        checkPossuiEvolucao.setSelected(true);
        else
        checkPossuiEvolucao.setSelected(false);
        if(tabelaPokemon.getValueAt(tabelaPokemon.getSelectedRow(), 8).toString() == "true")
        checkPodeEvoluir.setSelected(true);
        else
        checkPodeEvoluir.setSelected(false);
        if(tabelaPokemon.getValueAt(tabelaPokemon.getSelectedRow(), 9).toString() == "true")
        checkEmBatalha.setSelected(true);
        else
        checkEmBatalha.setSelected(false);
    }//GEN-LAST:event_tabelaPokemonMouseClicked

    private void buttonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSearchActionPerformed
        //Pesquisar pokemon por nome
        String nome = "%" + txtPesquisa.getText() + "%";

        PokemonDAO dao = new PokemonDAO();
        List<Pokemon> pokemonList = dao.buscar_pokemon_Nome(nome);
        DefaultTableModel dados = (DefaultTableModel) tabelaPokemon.getModel();
        dados.setNumRows(0);

        for(Pokemon p : pokemonList){
            dados.addRow(new Object[]{
                p.getId(),
                p.getNome(),
                p.getTipo(),
                p.getPontosCombate(),
                p.getDataCaptura(),
                p.getBatalhasVencidas(),
                p.getBatalhasPerdidas(),
                p.getPossuiEvolucao(),
                p.getPodeEvoluir(),
                p.getStatusBatalha()
            });
        }

    }//GEN-LAST:event_buttonSearchActionPerformed

    private void txtPesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaKeyPressed
        //Pesquisa ao digitar
        //Pesquisar pokemon por nome
        String nome = "%" + txtPesquisa.getText() + "%";

        PokemonDAO dao = new PokemonDAO();
        List<Pokemon> pokemonList = dao.buscar_pokemon_Nome(nome);
        DefaultTableModel dados = (DefaultTableModel) tabelaPokemon.getModel();
        dados.setNumRows(0);

        for(Pokemon p : pokemonList){
            dados.addRow(new Object[]{
                p.getId(),
                p.getNome(),
                p.getTipo(),
                p.getPontosCombate(),
                p.getDataCaptura(),
                p.getBatalhasVencidas(),
                p.getBatalhasPerdidas(),
                p.getPossuiEvolucao(),
                p.getPodeEvoluir(),
                p.getStatusBatalha()
            });
        }
    }//GEN-LAST:event_txtPesquisaKeyPressed

    private void txtPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisaActionPerformed

    private void checkPossuiEvolucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkPossuiEvolucaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkPossuiEvolucaoActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void checkPodeEvoluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkPodeEvoluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkPodeEvoluirActionPerformed

    private void checkEmBatalhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkEmBatalhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkEmBatalhaActionPerformed

    private void txtBatalhasPerdidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBatalhasPerdidasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBatalhasPerdidasActionPerformed

    private void txtBatalhasVencidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBatalhasVencidasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBatalhasVencidasActionPerformed

    private void txtPontosCombateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPontosCombateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPontosCombateActionPerformed

    private void txtDataCapturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataCapturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataCapturaActionPerformed

    private void txtTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipoActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PokemonForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PokemonForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PokemonForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PokemonForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PokemonForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel abaCadastro;
    private javax.swing.JPanel abaPesquisa;
    private javax.swing.JButton buttonEdit;
    private javax.swing.JButton buttonNew;
    private javax.swing.JButton buttonSave;
    private javax.swing.JButton buttonSearch;
    private javax.swing.JButton buttorDelete;
    private javax.swing.JCheckBox checkEmBatalha;
    private javax.swing.JCheckBox checkPodeEvoluir;
    private javax.swing.JCheckBox checkPossuiEvolucao;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaPokemon;
    private javax.swing.JTabbedPane telaPokemon;
    private javax.swing.JTextField txtBatalhasPerdidas;
    private javax.swing.JTextField txtBatalhasVencidas;
    private javax.swing.JFormattedTextField txtDataCaptura;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPesquisa;
    private javax.swing.JTextField txtPontosCombate;
    private javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables
}
