/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.pokedex.view;

import br.com.pokedex.dao.TreinadorDAO;
import br.com.pokedex.model.PokedexUtil;
import br.com.pokedex.model.Treinador;
import java.awt.Graphics;
import java.awt.Image;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nanda
 */
public class TreinadorForm extends javax.swing.JFrame {

    // Metodo listar na tabela
    public void listar_treinador(){
        
        TreinadorDAO dao = new TreinadorDAO();
        List<Treinador> treinadorList = dao.listar_treinadores();
        DefaultTableModel dados = (DefaultTableModel) tabelaTreinador.getModel();
        dados.setNumRows(0);
        
        for(Treinador t : treinadorList){
            dados.addRow(new Object[]{
                t.getNome(),
                t.getCpf(),
                t.getEmail(),
                t.getSenha(),
                t.getNivelAcesso(),
                t.getCelular(),
                t.getCEP(),
                t.getEndereco(),
                t.getNumero(),
                t.getComplemento(),
                t.getBairro(),
                t.getCidade(),
                t.getUf(),
                t.getDataIngresso(),
                t.getPokemonsCapturados(),
                t.getBatalhasPerdidas(),
                t.getBatalhasVencidas(),
                t.isStatusBatalha()
            });
        }
    }
    
    /**
     * Creates new form TreinadorForm
     */
    public TreinadorForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon = new ImageIcon(getClass().getResource("/images/telaFundoTreinadores.png"));
        Image image = icon.getImage();
        jDesktopPane1 = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){
                g.drawImage(image, 0, 0, 1080, 768, this);
            }
        };
        telaTreinadores = new javax.swing.JTabbedPane();
        abaCadastro = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCelular = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCep = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        txtCidade = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtComplemento = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtCpf = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();
        txtDataIngresso = new javax.swing.JFormattedTextField();
        boxUf = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        boxNivelAcesso = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtPokemonsCapturados = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtBatalhasVencidas = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtBatalhasPerdidas = new javax.swing.JTextField();
        checkEmBatalha = new javax.swing.JCheckBox();
        abaPesquisa = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtPesquisa = new javax.swing.JTextField();
        buttonSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaTreinador = new javax.swing.JTable();
        buttonNew = new javax.swing.JButton();
        buttonSave = new javax.swing.JButton();
        buttonEdit = new javax.swing.JButton();
        buttorDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1080, 768));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        telaTreinadores.setFont(new java.awt.Font("NATS", 0, 16));

        abaCadastro.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("NATS", 0, 18));
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nome:");

        txtNome.setBackground(new java.awt.Color(255, 255, 255));
        txtNome.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        txtEmail.setBackground(new java.awt.Color(255, 255, 255));
        txtEmail.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("NATS", 0, 18));
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("E-mail:");

        jLabel5.setFont(new java.awt.Font("NATS", 0, 18));
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Celular:");

        txtCelular.setBackground(new java.awt.Color(255, 255, 255));
        try {
            txtCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) # ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCelular.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("NATS", 0, 18));
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("CEP:");

        txtCep.setBackground(new java.awt.Color(255, 255, 255));
        try {
            txtCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCep.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        txtCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCepActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("NATS", 0, 18));
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Endereço:");

        txtEndereco.setBackground(new java.awt.Color(255, 255, 255));
        txtEndereco.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        txtEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnderecoActionPerformed(evt);
            }
        });

        txtNumero.setBackground(new java.awt.Color(255, 255, 255));
        txtNumero.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        txtNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("NATS", 0, 18));
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Nº:");

        jLabel9.setFont(new java.awt.Font("NATS", 0, 18));
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Bairro:");

        txtBairro.setBackground(new java.awt.Color(255, 255, 255));
        txtBairro.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        txtBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBairroActionPerformed(evt);
            }
        });

        txtCidade.setBackground(new java.awt.Color(255, 255, 255));
        txtCidade.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        txtCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCidadeActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("NATS", 0, 18));
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Cidade:");

        txtComplemento.setBackground(new java.awt.Color(255, 255, 255));
        txtComplemento.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        txtComplemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtComplementoActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("NATS", 0, 18));
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Complemento:");

        jLabel12.setFont(new java.awt.Font("NATS", 0, 18));
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("UF:");

        jLabel13.setFont(new java.awt.Font("NATS", 0, 18));
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("CPF:");

        txtCpf.setBackground(new java.awt.Color(255, 255, 255));
        try {
            txtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpf.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N

        jLabel14.setFont(new java.awt.Font("NATS", 0, 18));
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Data de ingresso:");

        txtDataIngresso.setBackground(new java.awt.Color(255, 255, 255));
        try {
            txtDataIngresso.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataIngresso.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        txtDataIngresso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataIngressoActionPerformed(evt);
            }
        });

        boxUf.setFont(new java.awt.Font("NATS", 0, 18));
        boxUf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        boxUf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxUfActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("NATS", 0, 18));
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Senha:");

        txtSenha.setBackground(new java.awt.Color(255, 255, 255));
        txtSenha.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        txtSenha.setToolTipText("");

        boxNivelAcesso.setFont(new java.awt.Font("NATS", 0, 18));
        boxNivelAcesso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Integrante", "Líder" }));
        boxNivelAcesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxNivelAcessoActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("NATS", 0, 18));
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Nível de acesso:");

        jLabel17.setFont(new java.awt.Font("NATS", 0, 18));
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Pokémons capturados:");

        txtPokemonsCapturados.setBackground(new java.awt.Color(255, 255, 255));
        txtPokemonsCapturados.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        txtPokemonsCapturados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPokemonsCapturadosActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("NATS", 0, 18));
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Batalhas vencidas:");

        txtBatalhasVencidas.setBackground(new java.awt.Color(255, 255, 255));
        txtBatalhasVencidas.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        txtBatalhasVencidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBatalhasVencidasActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("NATS", 0, 18));
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Batalhas perdidas:");

        txtBatalhasPerdidas.setBackground(new java.awt.Color(255, 255, 255));
        txtBatalhasPerdidas.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        txtBatalhasPerdidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBatalhasPerdidasActionPerformed(evt);
            }
        });

        checkEmBatalha.setBackground(new java.awt.Color(255, 255, 255));
        checkEmBatalha.setFont(new java.awt.Font("NATS", 0, 18));
        checkEmBatalha.setForeground(new java.awt.Color(0, 0, 0));
        checkEmBatalha.setText("Treinador em batalha");
        checkEmBatalha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkEmBatalhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout abaCadastroLayout = new javax.swing.GroupLayout(abaCadastro);
        abaCadastro.setLayout(abaCadastroLayout);
        abaCadastroLayout.setHorizontalGroup(
            abaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaCadastroLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(abaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(abaCadastroLayout.createSequentialGroup()
                        .addGroup(abaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(abaCadastroLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(boxNivelAcesso, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(abaCadastroLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDataIngresso, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(297, 297, 297)
                                .addComponent(jLabel17)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPokemonsCapturados, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addGroup(abaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(abaCadastroLayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBatalhasVencidas, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(abaCadastroLayout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBatalhasPerdidas, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(checkEmBatalha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 345, Short.MAX_VALUE))
                    .addGroup(abaCadastroLayout.createSequentialGroup()
                        .addGroup(abaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(abaCadastroLayout.createSequentialGroup()
                                .addGroup(abaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(abaCadastroLayout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel10))
                                    .addGroup(abaCadastroLayout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(abaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(abaCadastroLayout.createSequentialGroup()
                                        .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(38, 38, 38)
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(boxUf, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(abaCadastroLayout.createSequentialGroup()
                                .addGroup(abaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(abaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNome)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addGroup(abaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(abaCadastroLayout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(abaCadastroLayout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(73, 73, 73)
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(abaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(abaCadastroLayout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        abaCadastroLayout.setVerticalGroup(
            abaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaCadastroLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(abaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(abaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(abaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(abaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxUf, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(41, 41, 41)
                .addGroup(abaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtDataIngresso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(txtPokemonsCapturados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(txtBatalhasVencidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(abaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(abaCadastroLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(abaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(boxNivelAcesso, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)))
                    .addGroup(abaCadastroLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(abaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(txtBatalhasPerdidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(checkEmBatalha)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        telaTreinadores.addTab("Dados cadastrais", abaCadastro);

        abaPesquisa.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nome:");

        txtPesquisa.setBackground(new java.awt.Color(255, 255, 255));
        txtPesquisa.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        txtPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisaActionPerformed(evt);
            }
        });
        txtPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPesquisaKeyPressed(evt);
            }
        });

        buttonSearch.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        buttonSearch.setText("Pesquisar");
        buttonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSearchActionPerformed(evt);
            }
        });

        tabelaTreinador.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "CPF", "E-mail", "Senha", "Nível de acesso", "Celular", "CEP", "Endereço", "Número", "Complemento", "Bairro", "Cidade", "Estado", "Data de ingresso", "Pokemons capturados", "Batalhas vencidas", "Batalhas perdidas", "Em batalha"
            }
        ));
        tabelaTreinador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaTreinadorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaTreinador);

        javax.swing.GroupLayout abaPesquisaLayout = new javax.swing.GroupLayout(abaPesquisa);
        abaPesquisa.setLayout(abaPesquisaLayout);
        abaPesquisaLayout.setHorizontalGroup(
            abaPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaPesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(768, Short.MAX_VALUE))
            .addGroup(abaPesquisaLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1056, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        abaPesquisaLayout.setVerticalGroup(
            abaPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaPesquisaLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(abaPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE))
        );

        telaTreinadores.addTab("Pesquisar", abaPesquisa);

        buttonNew.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        buttonNew.setText("Novo");
        buttonNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNewActionPerformed(evt);
            }
        });

        buttonSave.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        buttonSave.setText("Criar");
        buttonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveActionPerformed(evt);
            }
        });

        buttonEdit.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        buttonEdit.setText("Salvar");
        buttonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditActionPerformed(evt);
            }
        });

        buttorDelete.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        buttorDelete.setText("Excluir");
        buttorDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttorDeleteActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(telaTreinadores, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(buttonNew, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(buttonSave, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(buttonEdit, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(buttorDelete, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(322, 322, 322)
                .addComponent(buttonNew, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttorDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(telaTreinadores)
                .addContainerGap())
        );

        jDesktopPane1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {buttonEdit, buttonNew, buttonSave, buttorDelete});

        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(telaTreinadores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buttonSave)
                        .addComponent(buttonEdit)
                        .addComponent(buttorDelete))
                    .addComponent(buttonNew, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(115, 115, 115))
        );

        jDesktopPane1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {buttonEdit, buttonNew, buttonSave, buttorDelete});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // Carrega a lista
        listar_treinador();
    }//GEN-LAST:event_formWindowActivated

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnderecoActionPerformed

    private void txtNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroActionPerformed

    private void txtBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBairroActionPerformed

    private void txtCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCidadeActionPerformed

    private void txtComplementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtComplementoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtComplementoActionPerformed

    private void txtDataIngressoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataIngressoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataIngressoActionPerformed

    private void boxUfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxUfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxUfActionPerformed

    private void txtPokemonsCapturadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPokemonsCapturadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPokemonsCapturadosActionPerformed

    private void txtBatalhasVencidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBatalhasVencidasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBatalhasVencidasActionPerformed

    private void txtBatalhasPerdidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBatalhasPerdidasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBatalhasPerdidasActionPerformed

    private void txtPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisaActionPerformed

    private void txtPesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaKeyPressed
        //Pesquisa ao digitar
        //Pesquisar treinador por nome
        String nome = "%" + txtPesquisa.getText() + "%";

        TreinadorDAO dao = new TreinadorDAO();
        List<Treinador> treinadorList = dao.buscar_treinador_Nome(nome);
        DefaultTableModel dados = (DefaultTableModel) tabelaTreinador.getModel();
        dados.setNumRows(0);

        for(Treinador t : treinadorList){
            dados.addRow(new Object[]{
                t.getNome(),
                t.getCpf(),
                t.getEmail(),
                t.getSenha(),
                t.getNivelAcesso(),
                t.getCelular(),
                t.getCEP(),
                t.getEndereco(),
                t.getNumero(),
                t.getComplemento(),
                t.getBairro(),
                t.getCidade(),
                t.getUf(),
                t.getDataIngresso(),
                t.getPokemonsCapturados(),
                t.getBatalhasPerdidas(),
                t.getBatalhasVencidas(),
                t.isStatusBatalha()
            });
        }
    }//GEN-LAST:event_txtPesquisaKeyPressed

    private void buttonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSearchActionPerformed
        //Pesquisar treinador por nome
        String nome = "%" + txtPesquisa.getText() + "%";

        TreinadorDAO dao = new TreinadorDAO();
        List<Treinador> treinadorList = dao.buscar_treinador_Nome(nome);
        DefaultTableModel dados = (DefaultTableModel) tabelaTreinador.getModel();
        dados.setNumRows(0);

        for(Treinador t : treinadorList){
            dados.addRow(new Object[]{
                t.getNome(),
                t.getCpf(),
                t.getEmail(),
                t.getSenha(),
                t.getNivelAcesso(),
                t.getCelular(),
                t.getCEP(),
                t.getEndereco(),
                t.getNumero(),
                t.getComplemento(),
                t.getBairro(),
                t.getCidade(),
                t.getUf(),
                t.getDataIngresso(),
                t.getPokemonsCapturados(),
                t.getBatalhasPerdidas(),
                t.getBatalhasVencidas(),
                t.isStatusBatalha()
            });
        }
    }//GEN-LAST:event_buttonSearchActionPerformed

    private void tabelaTreinadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaTreinadorMouseClicked
        // muda da aba de tabela de pesquisa para a aba de cadastro
        telaTreinadores.setSelectedIndex(0);
        txtNome.setText(tabelaTreinador.getValueAt(tabelaTreinador.getSelectedRow(), 0).toString());
        txtCpf.setText(tabelaTreinador.getValueAt(tabelaTreinador.getSelectedRow(), 1).toString());
        txtEmail.setText(tabelaTreinador.getValueAt(tabelaTreinador.getSelectedRow(), 2).toString());
        txtSenha.setText(tabelaTreinador.getValueAt(tabelaTreinador.getSelectedRow(), 3).toString());
        boxNivelAcesso.setSelectedItem(tabelaTreinador.getValueAt(tabelaTreinador.getSelectedRow(), 4).toString());
        txtCelular.setText(tabelaTreinador.getValueAt(tabelaTreinador.getSelectedRow(), 5).toString());
        txtCep.setText(tabelaTreinador.getValueAt(tabelaTreinador.getSelectedRow(), 6).toString());
        txtEndereco.setText(tabelaTreinador.getValueAt(tabelaTreinador.getSelectedRow(), 7).toString());
        txtNumero.setText(tabelaTreinador.getValueAt(tabelaTreinador.getSelectedRow(), 8).toString());
        txtComplemento.setText(tabelaTreinador.getValueAt(tabelaTreinador.getSelectedRow(), 9).toString());
        txtBairro.setText(tabelaTreinador.getValueAt(tabelaTreinador.getSelectedRow(), 10).toString());
        txtCidade.setText(tabelaTreinador.getValueAt(tabelaTreinador.getSelectedRow(), 11).toString());
        boxUf.setSelectedItem(tabelaTreinador.getValueAt(tabelaTreinador.getSelectedRow(), 12).toString());
        txtDataIngresso.setText(tabelaTreinador.getValueAt(tabelaTreinador.getSelectedRow(), 13).toString());
        txtPokemonsCapturados.setText(tabelaTreinador.getValueAt(tabelaTreinador.getSelectedRow(), 14).toString());
        txtBatalhasPerdidas.setText(tabelaTreinador.getValueAt(tabelaTreinador.getSelectedRow(), 15).toString());
        txtBatalhasVencidas.setText(tabelaTreinador.getValueAt(tabelaTreinador.getSelectedRow(), 16).toString());
        if(tabelaTreinador.getValueAt(tabelaTreinador.getSelectedRow(), 17).toString() == "true")
        checkEmBatalha.setSelected(true);
        else
        checkEmBatalha.setSelected(false);
    }//GEN-LAST:event_tabelaTreinadorMouseClicked

    private void buttonNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNewActionPerformed
        //Botao novo
        new PokedexUtil().limpa_dados(this.abaCadastro);
        telaTreinadores.setSelectedIndex(0);
    }//GEN-LAST:event_buttonNewActionPerformed

    private void buttonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveActionPerformed
        //botão de salvar
        Treinador treinador = new Treinador();

        treinador.setNome(txtNome.getText());
        treinador.setCpf(txtCpf.getText());
        treinador.setEmail(txtEmail.getText());
        treinador.setSenha(txtSenha.getText());
        treinador.setNivelAcesso(boxNivelAcesso.getSelectedItem().toString());
        treinador.setCelular(txtCelular.getText());
        treinador.setCEP(txtCep.getText());
        treinador.setEndereco(txtEndereco.getText());
        treinador.setNumero(Integer.parseInt(txtNumero.getText()));
        treinador.setComplemento(txtComplemento.getText());
        treinador.setBairro(txtBairro.getText());
        treinador.setCidade(txtCidade.getText());
        treinador.setUf(boxUf.getSelectedItem().toString());
        treinador.setDataIngresso(txtDataIngresso.getText());

        TreinadorDAO dao = new TreinadorDAO();
        dao.cadastrar_treinador(treinador);

        new PokedexUtil().limpa_dados(abaCadastro);
    }//GEN-LAST:event_buttonSaveActionPerformed

    private void buttonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditActionPerformed
        //botao de editar
        Treinador treinador = new Treinador();

        treinador.setNome(txtNome.getText());
        treinador.setCpf(txtCpf.getText());
        treinador.setEmail(txtEmail.getText());
        treinador.setSenha(txtSenha.getText());
        treinador.setNivelAcesso(boxNivelAcesso.getSelectedItem().toString());
        treinador.setCelular(txtCelular.getText());
        treinador.setCEP(txtCep.getText());
        treinador.setEndereco(txtEndereco.getText());
        treinador.setNumero(Integer.parseInt(txtNumero.getText()));
        treinador.setComplemento(txtComplemento.getText());
        treinador.setBairro(txtBairro.getText());
        treinador.setCidade(txtCidade.getText());
        treinador.setUf(boxUf.getSelectedItem().toString());
        treinador.setDataIngresso(txtDataIngresso.getText());
        treinador.setPokemonsCapturados(Integer.parseInt(txtPokemonsCapturados.getText()));
        treinador.setBatalhasPerdidas(Integer.parseInt(txtBatalhasPerdidas.getText()));
        treinador.setBatalhasVencidas(Integer.parseInt(txtBatalhasVencidas.getText()));
        treinador.setStatusBatalha(checkEmBatalha.isSelected());

        TreinadorDAO dao = new TreinadorDAO();
        dao.alterar_treinador(treinador);

        new PokedexUtil().limpa_dados(abaCadastro);
    }//GEN-LAST:event_buttonEditActionPerformed

    private void buttorDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttorDeleteActionPerformed
        //botao excluir
        Treinador treinador = new Treinador();

        treinador.setCpf(txtCpf.getText());

        TreinadorDAO dao = new TreinadorDAO();
        dao.excluir_treinador(treinador);

        new PokedexUtil().limpa_dados(abaCadastro);
    }//GEN-LAST:event_buttorDeleteActionPerformed

    private void checkEmBatalhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkEmBatalhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkEmBatalhaActionPerformed

    private void boxNivelAcessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxNivelAcessoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxNivelAcessoActionPerformed

    private void txtCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCepActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TreinadorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TreinadorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TreinadorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TreinadorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TreinadorForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel abaCadastro;
    private javax.swing.JPanel abaPesquisa;
    private javax.swing.JComboBox<String> boxNivelAcesso;
    private javax.swing.JComboBox<String> boxUf;
    private javax.swing.JButton buttonEdit;
    private javax.swing.JButton buttonNew;
    private javax.swing.JButton buttonSave;
    private javax.swing.JButton buttonSearch;
    private javax.swing.JButton buttorDelete;
    private javax.swing.JCheckBox checkEmBatalha;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaTreinador;
    private javax.swing.JTabbedPane telaTreinadores;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtBatalhasPerdidas;
    private javax.swing.JTextField txtBatalhasVencidas;
    private javax.swing.JFormattedTextField txtCelular;
    private javax.swing.JFormattedTextField txtCep;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtComplemento;
    private javax.swing.JFormattedTextField txtCpf;
    private javax.swing.JFormattedTextField txtDataIngresso;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtPesquisa;
    private javax.swing.JTextField txtPokemonsCapturados;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
